### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by rue-a** [slub/textract2page#16]
The tests have to be updated.

**Comment by rue-a** [comment]
I updated the test data. It turns out the tests are failing due to some issue with installing the package. @bertsky can you look into this?

**Comment by bertsky** [comment]
I believe this is really what we already discussed in [13](https://github.com/slub/textract2page/pull/13#issuecomment-1845155048). Merging #14 should suffice.

**Comment by bertsky** [comment]
Now as you can see CI fails because the tests are gone. In fact, your 0241430b65b463265041a9b76bc0ca55b37c6aa1 broke them. (Should be pytest textract2page/tests now.)

What was the reasoning here? IMO tests should **not** be part of the Python distribution.

**Comment by rue-a** [comment]
Not sure why I had them there. Moved them upwards and fixed the issues.
