### ISSUE TITLE
reading order: WORD-based vs. top-level based

### ISSUE THREAD

**Issue by bertsky** [slub/textract2page#24]
The current implementation extracts the ReadingOrder from the top-level parents of all `WORD` blocks (in the order of these word blocks). This seems to be necessary for cases with `TABLE` results.

However, for `LAYOUT_*` blocks, the results look much better if the top-level blocks are directly taken as the order – as implemented in #23.

For example, here is how both implementations compare:

| *current (WORD-based)* | *#23 (top-level based)* |
| --- | --- |
| ![sn1991-02-09_pr_0002 ro_word small](https://github.com/user-attachments/assets/83ba58ec-746b-448a-b55b-8a227719295b) | ![sn1991-02-09_pr_0002 ro_top-level small](https://github.com/user-attachments/assets/6c244f61-e7fe-4b71-9f1c-0ec50cc81155) |
| ![Ansiedlung_Korotschin_UZS_Sign_22a_0018 ro_word](https://github.com/user-attachments/assets/4d2c3ff9-a59b-43e9-ab70-e9238c272500) | ![Ansiedlung_Korotschin_UZS_Sign_22a_0018 ro_top-level](https://github.com/user-attachments/assets/d9b42d84-c198-4d00-8336-fe97a435ae03) |
| ![nd1969-01-21_3 ro_word small](https://github.com/user-attachments/assets/0f10af27-c464-47be-ba39-4065c99818dd) | ![nd1969-01-21_3 ro_top-level small](https://github.com/user-attachments/assets/b3c50321-7a18-4691-b05b-6c6f9827559b) |

The first page is a typical newspaper page (added to the tests in #23) and shows how #23 is better. 

The 2nd and 3rd example are taken from the test suite. The 2nd shows that the current implementation is better, because #23 places the table _after_ all the other regions.

In the 3rd example (`nd1969` test case) has AWS results which obviously look bad either way, with 2 false tables and many highly overlapping column regions.

**Comment by bertsky** [comment]
Also, from the 1st example it is obvious it would be better if the non-textual top-level blocks (image regions etc) would also be part of the extracted reading order (so for example one can post-process image captions differently).

**Comment by bertsky** [comment]
So regarding the open question how to deal with `LAYOUT_TABLE` – currently https://github.com/slub/textract2page/blob/55fe41689a1d301b22625db4bb7a66d5c3c42d6e/textract2page/convert_aws.py#L925-L927 – I found these interesting snippets:

https://github.com/aws-samples/amazon-textract-textractor/blob/82ceab8ca8460dcf6efebaf73e27b762dabb93b1/prettyprinter/textractprettyprinter/t_pretty_print_layout.py#L91-L99

https://github.com/aws-samples/amazon-textract-textractor/blob/82ceab8ca8460dcf6efebaf73e27b762dabb93b1/textractor/parsers/response_parser.py#L1090-L1111

Thus, apparently, for every `LAYOUT_TABLE` block we should expect to find a `TABLE` block of the same position and size, which in turn will contain the actual table hierarchy, but is itself not "in order". So we do need both. For the case where we do _not_ find any `LAYOUT_TABLE` object for each `TABLE` (or no `LAYOUT_*` results at all) we should keep our current word-order based approach.

**Comment by joewiz** [comment]
This is really interesting! Thank you for the great illustrations! (Were they produced by hand, or using a utility? If the latter, is it available?)

**Comment by bertsky** [comment]
> Were they produced by hand, or using a utility? If the latter, is it available?

The example images are produced via builtin screenshot facility of the native PAGE-XML view of [OCR-D Browser](https://github.com/hnesk/browse-ocrd/), a Gtk (i.e. Linux) GUI. Of which currently probably the best version is https://github.com/hnesk/browse-ocrd/pull/64. There is also a Docker version, which runs the Gtk app in the browser (also best built locally via `make docker`) – see instructions in readme.

For the sake of completeness, here are the results as of the current state of #23 (much better than shown above):

![sn1991-02-09_pr_0002 pageview web](https://github.com/user-attachments/assets/9feb14d7-ad44-4269-a5b2-83491d29a364)

![Ansiedlung_Korotschin_UZS_Sign_22a_0018 pageview web](https://github.com/user-attachments/assets/a24f983a-426f-42b3-880b-e6819130aa2c)

![nd1969-01-21_3 pageview web](https://github.com/user-attachments/assets/97ff1512-2faa-43c1-a6ea-c73fb5df0d2f)

Plus as a new example we stumbled upon cases of LINE within FIGURE (which must become TextRegions in ImageRegions) and PARAGRAPH within LIST (which must become TextRegion in TextRegion):

![sn1991-01-03_0001 pageview web](https://github.com/user-attachments/assets/8d10cb1b-027c-4280-9483-bdc69942789b)

**Comment by bertsky** [comment]
Note: OCR-D Browser expects a METS-XML representation in [OCR-D conventions](https://ocr-d.de/en/spec). If you just need a direct viewer, consider using [PRImA PageViewer](https://github.com/PRImA-Research-Lab/prima-page-viewer/releases), which is written in Java and thus platform-independent.
